# Path
export PATH=$PATH:$HOME/NanoBin/bin:$HOME/.rvm/bin
export GOPATH=$HOME

# Plugins (~/.oh-my-zsh/custom/plugins)
plugins=(git archlinux go golang cp ruby rvm bundler svn ubuntu centos yum pacman composer debian docker encode64 pip python sublime vi-mode tmux)

# Zsh Theme
export ZSH_THEME=flazz

# Aliases
alias h='history'
alias zrc='vim ~/.zshrc'
alias zrcl='vim ~/.zshrc.local'
alias vrc='vim ~/.vimrc'
alias vrcl='vim ~/.vimrc.local'
alias py='python3'
alias py2='python2'
alias py3='python3'
alias rb='ruby'
alias pl='perl'
alias gdif='git diff'
alias st='git status'
alias spider='scrapy runspider'
alias ydl='youtube-dl'
alias youtube-x='youtube-dl -x --audio-format vorbis --audio-quality 0'
alias act='source ~/venv/bin/activate'

# Load local config before initializing zsh
source $HOME/.zshrc.local

# Standard Zsh startup
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# "Double scp"
dscp() {
    # Pushes a file to a remote host home dir through a jump host
    # Example:
    # dscp fedjump sensu file.txt
    # dscp jump irma file.txt
    jump_host=$1
    dest_host=$2
    file_path=$3
    scp -oProxyJump=$jump_host $file_path $dest_host:
}
 
# "Double ssh"
dssh() {
    # Ssh through a jump host
    # Examples:
    # dssh fedjump sensu
    # dssh jump irma
    jump_host=$1
    dest_host=$2
    ssh -J $jump_host $dest_host
}

send_email() {
    to_address=$1
    message=$2
    /usr/sbin/sendmail "${to_address}" <<EOF
subject:ConsoleMailer
from:${USER}@$(hostname)
 
$message
EOF
    echo "Sent message to ${to_address}: $message"
}



###-tns-completion-start-###
if [ -f /home/nanodano/.tnsrc ]; then 
    source /home/nanodano/.tnsrc 
fi
###-tns-completion-end-###

set -i vi

