# Path
export PATH=$PATH:$HOME/NanoBin/bin:$HOME/.rvm/bin

# Plugins (~/.oh-my-zsh/custom/plugins)
plugins=(git archlinux go golang cp ruby rvm bundler svn ubuntu centos yum pacman composer debian docker encode64 pip python sublime)  

# Zsh Theme
export ZSH_THEME=takashiyoshida

# Aliases
alias h='history'
alias zrc='vim ~/.zshrc'
alias zrcl='vim ~/.zshrc.local'
alias py='python3'
alias py2='python2'
alias py3='python3'
alias rb='ruby'
alias pl='perl'
alias gdif='git diff'
alias st='git status'
alias spider='scrapy runspider'
alias ydl='youtube-dl'
alias youtube-x='youtube-dl -x --audio-format vorbis --audio-quality 0'

# Standard Zsh startup
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Local config
source $HOME/.zshrc.local
